### ISSUE TITLE
Generación de PWM basado en la lectura analógica

### ISSUE THREAD

**Issue by RebecaM94** [RebecaM94/Proyecto_Integrador#28]
Realizar la generación del PWM basado en la lectura de la entrada analógica que varía de 0 a 100. Con lo que se determinará el ciclo de trabajo de la señal de manera directa con la tarjeta de desarrollo Renesas.

**Definición de terminado.** Esta tarea puede transicionar a _"Done"_ cuando la tarjeta sea capaz de generar una onda cuadrada con ancho de pulso variable, basada en la lectura de la tarea #16

**Comment by pacpreciated** [comment]
Se encontró un problema de configuración del puerto de salida. El ticket es el #34

**Comment by pacpreciated** [comment]
Se realizó la verificación de la implementación de PWM

**Comment by pacpreciated** [comment]
Se configuró el PWM usando como dutyCycle el valor mapeado del ADC.
