### ISSUE TITLE
Crear temporizador por interrupción configurado a 100ms

### ISSUE THREAD

**Issue by RebecaM94** [RebecaM94/Proyecto_Integrador#29]
El sistema debe tener una base de tiempo en la cual ejecute todas las tareas.

**RS023** - El sistema debe tener un temporizador por interrupción configurado a 100 ms.

**Definición de terminado.** Esta tarea puede transicionar a terminado cuando el sistema sea capaz de ejecutar todas las acciones cada 100 ms.

**Comment by pacpreciated** [comment]
Se agregó una interrupción que sucede cada 100ms para la base de tiempo del control.
