### ISSUE TITLE
Planeación para la documentación inicial

### ISSUE THREAD

**Issue by RebecaM94** [RebecaM94/Proyecto_Integrador#9]
Se definirán las actividades generales para poder empezar con la asignación de tareas.

**Definición de terminado.** Esta tarea puede transicionar a "Done" cuando todos los puntos previamente establecidos hayan sido completados y aprobados por todos los miembros del equipo.

**Comment by pacpreciated** [comment]
Se realizaron las siguientes actividades: 
- Obtener platilla para empezar a desarrollar el Plan de Desarrollo de Software (DPS). 
- Definición de roles y responsabilidades siguiendo la metodología SCRUM. Queda pendiente el Product Owner
- Se calendarizaron las juntas de planeación, revisión y retrospectiva, siguiendo la metodología SCRUM.
- Definición de la duración de los sprints: 1 semana, empezando los lunes
- Empezar con el primer análisis de requisitos, en dónde se fueron listando los mismos a partir del documento de descripción del proyecto

**Definición de terminado**. Esta tarea puede transicionar a _"Done"_ cuando todos los puntos previamente establecidos hayan sido completados y aprobados por todos los miembros del equipo.
